spring.application.name=finalproject

spring.datasource.url=jdbc:oracle:thin:@//localhost:1521
spring.datasource.username=SYSTEM
spring.datasource.password=kianpagobo123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.dll-auto = none

spring.jpa.show-sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type=TRACE

# PayMongo test secret key (replace with your own)
paymongo.secretKey=sk_test_KjD3Xo8K1L5UpRhT7hS1Cty7
paymongo.public-key=pk_test_FQmLx6DDgUxAtKhfTY9kdD4a


